#!/bin/bash

# ==============================================================================
# SCRIPT: convert_metaphlan_gtdb.sh
#
# DESCRIPTION:
# Converts MetaPhlAn SGB-based taxonomic profiles to GTDB-based profiles.
# This script iterates through all individual sample profiles generated by
# MetaPhlAn for a given dataset and runs the `sgb_to_gtdb_profile.py`
# utility on each one.
#
# USAGE:
# ./convert_metaphlan_gtdb.sh <path_to_dataset_dir>
#
# EXAMPLE:
# ./convert_metaphlan_gtdb.sh ../SG_datasets/SG_39_Judith/
#
# ALL DATASET USAGES:
# chmod +x /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh
# /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh /home/haig/Repos/celiac-repository/SG_datasets/SG_39_Judith/
# /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh /home/haig/Repos/celiac-repository/SG_datasets/SG_80_Mouzan/
# /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh /home/haig/Repos/celiac-repository/SG_datasets/SG_95_Costigan/
# /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh /home/haig/Repos/celiac-repository/SG_datasets/SG_118_Leonard/
# /home/haig/Repos/celiac-repository/SG_scripts/convert_metaphlan_gtdb.sh /home/haig/Repos/celiac-repository/SG_datasets/SG_132_Francavilla/
#
# REQUIREMENTS:
# - `sgb_to_gtdb_profile.py` (from MetaPhlAn) must be in the system's PATH.
#
# ==============================================================================

# --- Configuration ---

# The subdirectory within the dataset directory where MetaPhlAn profiles are located.
METAPHLAN_OUT_SUBDIR="metaphlan_outputs"
# The subdirectory where the converted GTDB profiles will be stored.
GTDB_OUT_SUBDIR="gtdb"


# --- Script Body ---

# Exit immediately if a command exits with a non-zero status.
set -e

# Check for the correct number of arguments.
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_dataset_dir>"
    exit 1
fi

# Assign the first argument to a variable for clarity.
DATASET_DIR="$1"

# Check if the provided dataset directory exists.
if [ ! -d "$DATASET_DIR" ]; then
    echo "Error: Dataset directory not found at '$DATASET_DIR'"
    exit 1
fi

# Define the source and destination directories for the profiles.
PROFILES_DIR="${DATASET_DIR}/${METAPHLAN_OUT_SUBDIR}"
GTDB_PROFILES_DIR="${PROFILES_DIR}/${GTDB_OUT_SUBDIR}"

# Check if the MetaPhlAn output directory exists.
if [ ! -d "$PROFILES_DIR" ]; then
    echo "Error: MetaPhlAn output directory not found at '$PROFILES_DIR'"
    exit 1
fi

# Create the output directory for GTDB profiles if it doesn't exist.
echo "Creating GTDB output directory: $GTDB_PROFILES_DIR"
mkdir -p "$GTDB_PROFILES_DIR"

# Find all MetaPhlAn profile files and loop through them.
# Using find is more robust than a simple glob, especially with many files.
echo "Searching for profiles in: $PROFILES_DIR"
find "$PROFILES_DIR" -maxdepth 1 -name "*_profile.txt" | while read -r profile_file; do

    # Get the base name of the file (e.g., 'sample1_profile.txt').
    base_name=$(basename "$profile_file")

    # Define the path for the output file.
    output_file="${GTDB_PROFILES_DIR}/${base_name}"

    echo "Converting: $base_name"

    # Run the conversion script.
    sgb_to_gtdb_profile.py -i "$profile_file" -o "$output_file"

done

echo "---"
echo "Conversion complete for dataset: $(basename "$DATASET_DIR")"
echo "GTDB profiles are located in: $GTDB_PROFILES_DIR"
echo "---"
